/**
 * `clesty compile <spec> --output <path>` — the orchestrator.
 *
 * Closes #764 (CLI entry point) and #765 (deno-compile bundle step).
 *
 * Pipeline:
 *   1. Parse args → `{ spec, output, allowRefRoot }`.
 *   2. `Preflight.check(spec)` (#107) — refuse unsupported openapi versions.
 *   3. `RefSafety.checkRefSafety(spec, { allowRefRoot })` (#241) — refuse
 *      $refs that escape the allowed root.
 *   4. `Codegen.emit(spec)` (#130 / #151 / #152 / #153 / #154 / #155 /
 *      #156 / #157 / #159 / #162 / #163) — emit the per-operation CLI
 *      subcommand source.
 *   5. Compose an entry TypeScript file that wires the codegen source
 *      to commander + the runtime response matcher.
 *   6. `deno compile --output <path>` the entry file → self-contained
 *      native binary the user can drop into CI.
 *
 * The `client.<opId>(...)` calls that codegen emits will be backed by
 * hey-api's typed client once #766 lands; until then the binary's
 * subcommand `--help` is correct (the headline #764/#765 contract) but
 * action bodies will throw at runtime.
 *
 * @module
 */

import { isAbsolute, join, resolve } from "@std/path";
import { Compile, Preflight } from "./compile/preflight.ts";
import { checkRefSafety, RefEscapesRoot } from "./compile/ref-safety.ts";
import { emit } from "./compile/codegen.ts";

const USAGE = `\
Usage: clesty compile <spec> --output <bin> [options]

Compile an OpenAPI 3 document into a self-contained CLI binary.

Arguments:
  <spec>                      Path or URL to the OpenAPI document.

Required options:
  --output <bin>              Path to write the compiled binary.

Options:
  --allow-ref-root <dir>      Broaden the allowed root for external $refs.
  -h, --help                  Show this help.

Exit codes:
  0  success
  2  usage error (missing/invalid args)
  3  preflight failure (Compile.MissingVersion, .UnsupportedVersion, etc.)
  4  ref-safety failure (RefEscapesRoot)
  5  codegen / bundle failure
`;

type CompileArgs = {
  spec: string;
  output: string;
  allowRefRoot?: string;
};

export class UsageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "UsageError";
  }
}

/** Parse `clesty compile ...` argv into typed args. */
export function parseCompileArgs(argv: string[]): CompileArgs {
  let spec: string | null = null;
  let output: string | null = null;
  let allowRefRoot: string | undefined;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--output" || a === "-o") {
      output = argv[++i];
      if (output === undefined) throw new UsageError("--output requires a value");
    } else if (a === "--allow-ref-root") {
      allowRefRoot = argv[++i];
      if (allowRefRoot === undefined) {
        throw new UsageError("--allow-ref-root requires a value");
      }
    } else if (a === "-h" || a === "--help") {
      throw new UsageError("__HELP__");
    } else if (a.startsWith("-")) {
      throw new UsageError(`unknown option: ${a}`);
    } else if (spec === null) {
      spec = a;
    } else {
      throw new UsageError(`unexpected argument: ${a}`);
    }
  }
  if (spec === null) throw new UsageError("missing required argument <spec>");
  if (output === null) throw new UsageError("missing required option --output <bin>");
  return { spec, output, allowRefRoot };
}

/** Compose a TypeScript entry file that wraps the codegen source in a
 * runnable program. The entry file is what `deno compile` consumes. */
function composeEntry(codegenSource: string): string {
  // Minimal `program` shim mimicking commander's chained API. Stays
  // self-contained so the compiled binary has no runtime dependency on
  // commander itself — keeps the artifact small. When the runtime work
  // (#768) lands, swap in the real commander or hey-api's runtime client.
  return `\
// Generated by clesty. Do not edit.
// deno-lint-ignore-file no-explicit-any

type Action = (opts: any) => void | Promise<void>;
type CmdOpt = { flag: string; description: string; required: boolean };
type Cmd = {
  name: string;
  description: string;
  opts: CmdOpt[];
  action: Action | null;
};

const commands: Cmd[] = [];
let current: Cmd | null = null;

const program = {
  command(name: string, description: string = "") {
    current = { name, description, opts: [], action: null };
    commands.push(current);
    return chain;
  },
};

const chain = {
  requiredOption(flag: string, description: string) {
    current!.opts.push({ flag, description, required: true });
    return chain;
  },
  option(flag: string, description: string) {
    current!.opts.push({ flag, description, required: false });
    return chain;
  },
  action(fn: Action) {
    current!.action = fn;
    return chain;
  },
};

// hey-api typed client — populated by #766. Until then, action bodies
// throw a clear error so users learn the runtime is not yet wired.
const client = new Proxy({}, {
  get(_, prop) {
    return () => {
      throw new Error(
        \`clesty runtime not implemented yet (#768). The compiled binary's \` +
          \`--help is accurate, but \\\`\${String(prop)}\\\` cannot make an HTTP call.\`,
      );
    };
  },
}) as any;

${codegenSource}

function parseFlags(opts: CmdOpt[], rest: string[]): Record<string, string> {
  const out: Record<string, string> = {};
  const byFlag: Record<string, CmdOpt> = {};
  for (const o of opts) {
    const head = o.flag.split(/\\s+/, 1)[0];
    byFlag[head] = o;
  }
  for (let i = 0; i < rest.length; i++) {
    const a = rest[i];
    const opt = byFlag[a];
    if (!opt) throw new Error(\`unknown option: \${a}\`);
    const v = rest[++i];
    if (v === undefined) throw new Error(\`option \${a} requires a value\`);
    const name = a.replace(/^--/, "");
    out[name] = v;
  }
  for (const o of opts) {
    if (!o.required) continue;
    const head = o.flag.split(/\\s+/, 1)[0].replace(/^--/, "");
    if (!(head in out)) throw new Error(\`required option missing: --\${head}\`);
  }
  return out;
}

function helpText(): string {
  const lines = ["Usage: <bin> <subcommand> [options]", "", "Subcommands:"];
  for (const c of commands) {
    lines.push(\`  \${c.name}  \${c.description ?? ""}\`);
  }
  return lines.join("\\n");
}

async function main() {
  const argv = (globalThis as any).Deno?.args ?? [];
  if (argv.length === 0 || argv[0] === "-h" || argv[0] === "--help") {
    console.log(helpText());
    return;
  }
  const sub = argv[0];
  const rest = argv.slice(1);
  if (rest.includes("--help") || rest.includes("-h")) {
    const c = commands.find((x) => x.name === sub);
    if (!c) {
      console.error(\`unknown subcommand: \${sub}\`);
      (globalThis as any).Deno?.exit(2);
      return;
    }
    console.log(\`Usage: <bin> \${sub} [options]\`);
    console.log("");
    console.log(c.description ?? "");
    if (c.opts.length > 0) {
      console.log("");
      console.log("Options:");
      for (const o of c.opts) {
        console.log(\`  \${o.flag}  \${o.description}\${o.required ? " (required)" : ""}\`);
      }
    }
    return;
  }
  const c = commands.find((x) => x.name === sub);
  if (!c) {
    console.error(\`unknown subcommand: \${sub}\`);
    (globalThis as any).Deno?.exit(2);
    return;
  }
  try {
    const opts = parseFlags(c.opts, rest);
    if (c.action) await c.action(opts);
  } catch (e) {
    console.error((e as Error).message);
    (globalThis as any).Deno?.exit(1);
  }
}

await main();
`;
}

/** Compile a spec into a self-contained binary at `args.output`. */
export async function compile(args: CompileArgs): Promise<void> {
  const specPath = isAbsolute(args.spec) ? args.spec : resolve(args.spec);

  // 1. Preflight (#107).
  await Preflight.check(specPath);

  // 2. Ref-safety (#241).
  await checkRefSafety(specPath, { allowRefRoot: args.allowRefRoot });

  // 3. Codegen (#130 etc.).
  const result = await emit(specPath);

  // 4. Compose entry.
  const entry = composeEntry(result.source);

  // 5. Write entry to a temp file and run `deno compile`.
  const tmp = await Deno.makeTempDir({ prefix: "clesty-bundle-" });
  try {
    const entryPath = join(tmp, "entry.ts");
    await Deno.writeTextFile(entryPath, entry);
    const compileCmd = new Deno.Command(Deno.execPath(), {
      args: ["compile", "--quiet", "--allow-net", "--output", args.output, entryPath],
      stdout: "piped",
      stderr: "piped",
    });
    const out = await compileCmd.output();
    if (out.code !== 0) {
      const stderr = new TextDecoder().decode(out.stderr);
      throw new Error(`deno compile failed (exit ${out.code}):\n${stderr}`);
    }
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
}

/** Top-level dispatcher: argv[0] is the verb. */
export async function main(argv: string[]): Promise<number> {
  if (argv.length === 0 || argv[0] === "-h" || argv[0] === "--help") {
    console.log(USAGE);
    return 0;
  }
  const verb = argv[0];
  if (verb !== "compile") {
    console.error(`unknown verb: ${verb}\n\n${USAGE}`);
    return 2;
  }

  let parsed: CompileArgs;
  try {
    parsed = parseCompileArgs(argv.slice(1));
  } catch (e) {
    if (e instanceof UsageError) {
      if (e.message === "__HELP__") {
        console.log(USAGE);
        return 0;
      }
      console.error(`error: ${e.message}\n\n${USAGE}`);
      return 2;
    }
    throw e;
  }

  try {
    await compile(parsed);
    return 0;
  } catch (e) {
    const err = e as Error;
    const name = err.name ?? err.constructor?.name ?? "Error";
    // Surface error class name so test assertions match (#107, #241).
    console.error(`${name}: ${err.message}`);
    if (
      err instanceof Compile.MissingVersion ||
      err instanceof Compile.InvalidVersion ||
      err instanceof Compile.UnsupportedVersion
    ) return 3;
    if (err instanceof RefEscapesRoot) return 4;
    return 5;
  }
}

if (import.meta.main) {
  const code = await main(Deno.args);
  Deno.exit(code);
}
