/**
 * `clesty compile <spec> --output <path>` — the orchestrator.
 *
 * Closes #764 (CLI entry point) and #765 (deno-compile bundle step).
 *
 * Pipeline:
 *   1. Parse args → `{ spec, output, allowRefRoot }`.
 *   2. `Preflight.check(spec)` (#107) — refuse unsupported openapi versions.
 *   3. `RefSafety.checkRefSafety(spec, { allowRefRoot })` (#241) — refuse
 *      $refs that escape the allowed root.
 *   4. `Codegen.emit(spec)` (#130 / #151 / #152 / #153 / #154 / #155 /
 *      #156 / #157 / #159 / #162 / #163) — emit the per-operation CLI
 *      subcommand source.
 *   5. Compose an entry TypeScript file that wires the codegen source
 *      to commander + the runtime response matcher.
 *   6. `deno compile --output <path>` the entry file → self-contained
 *      native binary the user can drop into CI.
 *
 * The `client.<opId>(...)` calls that codegen emits will be backed by
 * hey-api's typed client once #766 lands; until then the binary's
 * subcommand `--help` is correct (the headline #764/#765 contract) but
 * action bodies will throw at runtime.
 *
 * @module
 */

import { isAbsolute, join, resolve } from "@std/path";
import * as Yaml from "@std/yaml";
import { createClient } from "@hey-api/openapi-ts";
import { Compile, Preflight } from "./compile/preflight.ts";
import { checkRefSafety, RefEscapesRoot } from "./compile/ref-safety.ts";
import { emit } from "./compile/codegen.ts";

const USAGE = `\
Usage: clesty compile <spec> --output <bin> [options]

Compile an OpenAPI 3 document into a self-contained CLI binary.

Arguments:
  <spec>                      Path, URL, or '-' (read from stdin) for
                              the OpenAPI document.

Required options:
  --output <bin>              Path to write the compiled binary.

Options:
  --allow-ref-root <dir>      Broaden the allowed root for external $refs.
  -h, --help                  Show this help.

Exit codes:
  0  success
  2  usage error (missing/invalid args)
  3  preflight failure (Compile.MissingVersion, .UnsupportedVersion, etc.)
  4  ref-safety failure (RefEscapesRoot)
  5  codegen / bundle failure
`;

type CompileArgs = {
  spec: string;
  output: string;
  allowRefRoot?: string;
};

export class UsageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "UsageError";
  }
}

/** Parse `clesty compile ...` argv into typed args. */
export function parseCompileArgs(argv: string[]): CompileArgs {
  let spec: string | null = null;
  let output: string | null = null;
  let allowRefRoot: string | undefined;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--output" || a === "-o") {
      output = argv[++i];
      if (output === undefined) throw new UsageError("--output requires a value");
    } else if (a === "--allow-ref-root") {
      allowRefRoot = argv[++i];
      if (allowRefRoot === undefined) {
        throw new UsageError("--allow-ref-root requires a value");
      }
    } else if (a === "-h" || a === "--help") {
      throw new UsageError("__HELP__");
    } else if (a === "-" && spec === null) {
      // Bare `-` is the conventional stdin sentinel; takes the
      // positional spec slot.
      spec = a;
    } else if (a.startsWith("-")) {
      throw new UsageError(`unknown option: ${a}`);
    } else if (spec === null) {
      spec = a;
    } else {
      throw new UsageError(`unexpected argument: ${a}`);
    }
  }
  if (spec === null) throw new UsageError("missing required argument <spec>");
  if (output === null) throw new UsageError("missing required option --output <bin>");
  return { spec, output, allowRefRoot };
}

/** Compose a TypeScript entry file that wraps the codegen source in a
 * runnable program. The entry file is what `deno compile` consumes. */
function composeEntry(codegenSource: string): string {
  // Minimal `program` shim mimicking commander's chained API. Stays
  // self-contained so the compiled binary has no runtime dependency on
  // commander itself — keeps the artifact small.
  //
  // `client` is bound to hey-api's generated SDK (#766) — every operation
  // exported from `./generated/sdk.gen.ts` is reachable as `client.<opId>`.
  // The runtime CLI/UX layer (formatter, exit codes, auth flag wiring)
  // lands in #768.
  return `\
// Generated by clesty. Do not edit.
// deno-lint-ignore-file no-explicit-any

import * as sdk from "./generated/sdk.gen.ts";

type Action = (opts: any) => void | Promise<void>;
type CmdOpt = { flag: string; description: string; required: boolean };
type Cmd = {
  name: string;
  description: string;
  opts: CmdOpt[];
  action: Action | null;
};

const commands: Cmd[] = [];
let current: Cmd | null = null;

const program = {
  command(name: string, description: string = "") {
    current = { name, description, opts: [], action: null };
    commands.push(current);
    return chain;
  },
};

const chain = {
  requiredOption(flag: string, description: string) {
    current!.opts.push({ flag, description, required: true });
    return chain;
  },
  option(flag: string, description: string) {
    current!.opts.push({ flag, description, required: false });
    return chain;
  },
  action(fn: Action) {
    current!.action = fn;
    return chain;
  },
};

const client = sdk as any;

${codegenSource}

function parseFlags(opts: CmdOpt[], rest: string[]): Record<string, string> {
  const out: Record<string, string> = {};
  const byFlag: Record<string, CmdOpt> = {};
  for (const o of opts) {
    const head = o.flag.split(/\\s+/, 1)[0];
    byFlag[head] = o;
  }
  for (let i = 0; i < rest.length; i++) {
    const a = rest[i];
    const opt = byFlag[a];
    if (!opt) throw new Error(\`unknown option: \${a}\`);
    const v = rest[++i];
    if (v === undefined) throw new Error(\`option \${a} requires a value\`);
    const name = a.replace(/^--/, "");
    out[name] = v;
  }
  for (const o of opts) {
    if (!o.required) continue;
    const head = o.flag.split(/\\s+/, 1)[0].replace(/^--/, "");
    if (!(head in out)) throw new Error(\`required option missing: --\${head}\`);
  }
  return out;
}

function helpText(): string {
  const lines = ["Usage: <bin> <subcommand> [options]", "", "Subcommands:"];
  for (const c of commands) {
    lines.push(\`  \${c.name}  \${c.description ?? ""}\`);
  }
  return lines.join("\\n");
}

async function main() {
  const argv = (globalThis as any).Deno?.args ?? [];
  if (argv.length === 0 || argv[0] === "-h" || argv[0] === "--help") {
    console.log(helpText());
    return;
  }
  const sub = argv[0];
  const rest = argv.slice(1);
  if (rest.includes("--help") || rest.includes("-h")) {
    const c = commands.find((x) => x.name === sub);
    if (!c) {
      console.error(\`unknown subcommand: \${sub}\`);
      (globalThis as any).Deno?.exit(2);
      return;
    }
    console.log(\`Usage: <bin> \${sub} [options]\`);
    console.log("");
    console.log(c.description ?? "");
    if (c.opts.length > 0) {
      console.log("");
      console.log("Options:");
      for (const o of c.opts) {
        console.log(\`  \${o.flag}  \${o.description}\${o.required ? " (required)" : ""}\`);
      }
    }
    return;
  }
  const c = commands.find((x) => x.name === sub);
  if (!c) {
    console.error(\`unknown subcommand: \${sub}\`);
    (globalThis as any).Deno?.exit(2);
    return;
  }
  try {
    const opts = parseFlags(c.opts, rest);
    if (c.action) await c.action(opts);
  } catch (e) {
    console.error((e as Error).message);
    (globalThis as any).Deno?.exit(1);
  }
}

await main();
`;
}

type SpecSource =
  | { kind: "path"; path: string }
  | { kind: "url"; url: string }
  | { kind: "stdin" };

/** Classify `args.spec`. URL inputs pass through unchanged; absolute /
 * relative filesystem paths get absolutized; the literal `-` means
 * "read from stdin". The stdin case is materialized to a temp file
 * inside `compile()` so preflight, ref-safety, codegen, and hey-api
 * each consume the same bytes — the tee/buffer/handoff design called
 * out in #766 §Scope. */
function classifySpec(spec: string): SpecSource {
  if (spec === "-") return { kind: "stdin" };
  if (spec.startsWith("http://") || spec.startsWith("https://") || spec.startsWith("file:")) {
    return { kind: "url", url: spec };
  }
  return { kind: "path", path: isAbsolute(spec) ? spec : resolve(spec) };
}

/** Drain the readable stream into a Uint8Array. Used to materialize a
 * stdin spec to disk so all downstream consumers see the same bytes. */
async function readAll(stream: ReadableStream<Uint8Array>): Promise<Uint8Array> {
  const chunks: Uint8Array[] = [];
  let total = 0;
  const reader = stream.getReader();
  try {
    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      if (value) {
        chunks.push(value);
        total += value.byteLength;
      }
    }
  } finally {
    reader.releaseLock();
  }
  const out = new Uint8Array(total);
  let off = 0;
  for (const chunk of chunks) {
    out.set(chunk, off);
    off += chunk.byteLength;
  }
  return out;
}

/** Rewrite an error's `origin` (and `message` substring) from a temp
 * path to `<stdin>` so the caller sees the spec identifier they
 * actually passed (#107 contract: stream origins surface as `<stdin>`,
 * not the temp file the orchestrator chose to materialize them to). */
function withOrigin<E extends Error & { origin?: string }>(
  err: E,
  realOrigin: string,
  visibleOrigin: string,
): E {
  if (err.origin === realOrigin) err.origin = visibleOrigin;
  if (typeof err.message === "string" && err.message.includes(realOrigin)) {
    err.message = err.message.split(realOrigin).join(visibleOrigin);
  }
  return err;
}

/** Compile a spec into a self-contained binary at `args.output`. */
export async function compile(args: CompileArgs): Promise<void> {
  const spec = classifySpec(args.spec);

  // The bundle tmp dir holds the hey-api SDK output, the composed
  // entry.ts, and (for stdin specs) the materialized spec file.
  const tmp = await Deno.makeTempDir({ prefix: "clesty-bundle-" });

  try {
    // Stream handoff: stdin → temp file → all downstream consumers.
    // Writing once to disk and passing the path is the simplest
    // tee/buffer that satisfies preflight + ref-safety + hey-api
    // (which all want a path or URL, not a live stream).
    //
    // `inputForHeyApi` is what we hand to hey-api (path / URL).
    // `originOverride` (when non-null) tells the error-rewriting helper
    // what to substitute in the surfaced origin so the user sees the
    // identifier they actually typed (path / URL / `<stdin>`) rather
    // than the temp file we chose internally.
    let inputForHeyApi: string;
    let originOverride: string | null = null;
    if (spec.kind === "stdin") {
      const bytes = await readAll(Deno.stdin.readable);
      inputForHeyApi = join(tmp, "stdin-spec.yaml");
      await Deno.writeFile(inputForHeyApi, bytes);
      originOverride = "<stdin>";
    } else if (spec.kind === "url") {
      inputForHeyApi = spec.url;
    } else {
      inputForHeyApi = spec.path;
    }

    // 1. Preflight (#107) — accepts paths and URLs. Rewrite the
    // surfaced origin if we materialized stdin to a temp file.
    try {
      await Preflight.check(spec.kind === "url" ? new URL(inputForHeyApi) : inputForHeyApi);
    } catch (e) {
      if (originOverride !== null) {
        throw withOrigin(e as Error & { origin?: string }, inputForHeyApi, originOverride);
      }
      throw e;
    }

    // 2. Ref-safety (#241) — only meaningful for local-on-disk specs
    // with a meaningful enclosing directory. URL inputs pull over
    // HTTPS; stdin specs are unmoored (no caller-relative root). The
    // boundary check applies only to disk paths the caller named.
    if (spec.kind === "path") {
      await checkRefSafety(inputForHeyApi, { allowRefRoot: args.allowRefRoot });
    }

    // 3. Codegen (#130 etc.). The string-overload uses Deno.readTextFile
    // which doesn't follow URLs, so for URL inputs we fetch the bytes
    // ourselves and feed the parsed doc to the synchronous overload.
    let result;
    if (spec.kind === "url") {
      const res = await fetch(inputForHeyApi);
      if (!res.ok) {
        throw new Error(`fetch ${inputForHeyApi} failed: ${res.status} ${res.statusText}`);
      }
      const text = await res.text();
      const doc = Yaml.parse(text) as Record<string, unknown>;
      result = emit(doc);
    } else {
      result = await emit(inputForHeyApi);
    }

    // 4. hey-api: produce the typed SDK at <tmp>/generated/. Wrap any
    // throw as Compile.HeyApiFailure so callers get a uniform error
    // surface (#107 §"Errors"). Hey-api accepts both filesystem paths
    // and remote URLs as `input`.
    try {
      await createClient({
        input: inputForHeyApi,
        output: { path: join(tmp, "generated") },
        plugins: ["@hey-api/client-fetch"],
      });
    } catch (cause) {
      const visibleOrigin = originOverride ?? inputForHeyApi;
      throw new Compile.HeyApiFailure(visibleOrigin, cause);
    }

    // 5. Compose the entry — the `import "./generated/sdk.gen.ts"` is
    // resolved by deno compile inside the tmp dir.
    const entry = composeEntry(result.source);
    const entryPath = join(tmp, "entry.ts");
    await Deno.writeTextFile(entryPath, entry);

    // 6. deno compile → self-contained binary at args.output.
    // --sloppy-imports because hey-api's generated TS uses Node-style
    // relative imports without `.ts` extensions; Deno requires explicit
    // extensions otherwise.
    const compileCmd = new Deno.Command(Deno.execPath(), {
      args: [
        "compile",
        "--quiet",
        "--allow-net",
        "--sloppy-imports",
        "--output",
        args.output,
        entryPath,
      ],
      stdout: "piped",
      stderr: "piped",
    });
    const out = await compileCmd.output();
    if (out.code !== 0) {
      const stderr = new TextDecoder().decode(out.stderr);
      throw new Error(`deno compile failed (exit ${out.code}):\n${stderr}`);
    }
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
}

/** Top-level dispatcher: argv[0] is the verb. */
export async function main(argv: string[]): Promise<number> {
  if (argv.length === 0 || argv[0] === "-h" || argv[0] === "--help") {
    console.log(USAGE);
    return 0;
  }
  const verb = argv[0];
  if (verb !== "compile") {
    console.error(`unknown verb: ${verb}\n\n${USAGE}`);
    return 2;
  }

  let parsed: CompileArgs;
  try {
    parsed = parseCompileArgs(argv.slice(1));
  } catch (e) {
    if (e instanceof UsageError) {
      if (e.message === "__HELP__") {
        console.log(USAGE);
        return 0;
      }
      console.error(`error: ${e.message}\n\n${USAGE}`);
      return 2;
    }
    throw e;
  }

  try {
    await compile(parsed);
    return 0;
  } catch (e) {
    const err = e as Error;
    const name = err.name ?? err.constructor?.name ?? "Error";
    // Surface error class name so test assertions match (#107, #241).
    console.error(`${name}: ${err.message}`);
    if (
      err instanceof Compile.MissingVersion ||
      err instanceof Compile.InvalidVersion ||
      err instanceof Compile.UnsupportedVersion
    ) return 3;
    if (err instanceof RefEscapesRoot) return 4;
    if (err instanceof Compile.HeyApiFailure) return 5;
    return 5;
  }
}

if (import.meta.main) {
  const code = await main(Deno.args);
  Deno.exit(code);
}
