/**
 * `clesty compile <spec> --output <path>` — the orchestrator.
 *
 * Closes #764 (CLI entry point) and #765 (deno-compile bundle step).
 *
 * Pipeline:
 *   1. Parse args → `{ spec, output, allowRefRoot }`.
 *   2. `Preflight.check(spec)` (#107) — refuse unsupported openapi versions.
 *   3. `RefSafety.checkRefSafety(spec, { allowRefRoot })` (#241) — refuse
 *      $refs that escape the allowed root.
 *   4. `Codegen.emit(spec)` (#130 / #151 / #152 / #153 / #154 / #155 /
 *      #156 / #157 / #159 / #162 / #163) — emit the per-operation CLI
 *      subcommand source.
 *   5. Compose an entry TypeScript file that wires the codegen source
 *      to commander + the runtime response matcher.
 *   6. `deno compile --output <path>` the entry file → self-contained
 *      native binary the user can drop into CI.
 *
 * The `client.<opId>(...)` calls that codegen emits will be backed by
 * hey-api's typed client once #766 lands; until then the binary's
 * subcommand `--help` is correct (the headline #764/#765 contract) but
 * action bodies will throw at runtime.
 *
 * @module
 */

import { fromFileUrl, isAbsolute, join, resolve } from "@std/path";
import { createClient } from "@hey-api/openapi-ts";
import { Compile, Preflight } from "./compile/preflight.ts";
import { checkRefSafety, RefEscapesRoot } from "./compile/ref-safety.ts";
import { emit } from "./compile/codegen.ts";

const USAGE = `\
Usage: clesty compile <spec> --output <bin> [options]

Compile an OpenAPI 3 document into a self-contained CLI binary.

Arguments:
  <spec>                      Path, URL, or '-' (read from stdin) for
                              the OpenAPI document.

Required options:
  --output <bin>              Path to write the compiled binary.

Options:
  --allow-ref-root <dir>      Broaden the allowed root for external $refs.
  -h, --help                  Show this help.

Exit codes:
  0  success
  2  usage error (missing/invalid args)
  3  preflight failure (Compile.MissingVersion, .UnsupportedVersion, etc.)
  4  ref-safety failure (RefEscapesRoot)
  5  codegen / bundle failure
`;

type CompileArgs = {
  spec: string;
  output: string;
  allowRefRoot?: string;
};

export class UsageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "UsageError";
  }
}

/** Parse `clesty compile ...` argv into typed args. */
export function parseCompileArgs(argv: string[]): CompileArgs {
  let spec: string | null = null;
  let output: string | null = null;
  let allowRefRoot: string | undefined;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--output" || a === "-o") {
      output = argv[++i];
      if (output === undefined) throw new UsageError("--output requires a value");
    } else if (a === "--allow-ref-root") {
      allowRefRoot = argv[++i];
      if (allowRefRoot === undefined) {
        throw new UsageError("--allow-ref-root requires a value");
      }
    } else if (a === "-h" || a === "--help") {
      throw new UsageError("__HELP__");
    } else if (a === "-" && spec === null) {
      // Bare `-` is the conventional stdin sentinel; takes the
      // positional spec slot.
      spec = a;
    } else if (a.startsWith("-")) {
      throw new UsageError(`unknown option: ${a}`);
    } else if (spec === null) {
      spec = a;
    } else {
      throw new UsageError(`unexpected argument: ${a}`);
    }
  }
  if (spec === null) throw new UsageError("missing required argument <spec>");
  if (output === null) throw new UsageError("missing required option --output <bin>");
  return { spec, output, allowRefRoot };
}

/** Compose a TypeScript entry file that wraps the codegen source in a
 * runnable program. The entry file is what `deno compile` consumes. */
function composeEntry(codegenSource: string): string {
  // Minimal `program` shim mimicking commander's chained API. Stays
  // self-contained so the compiled binary has no runtime dependency on
  // commander itself — keeps the artifact small.
  //
  // `client` is bound to hey-api's generated SDK (#766) — every operation
  // exported from `./generated/sdk.gen.ts` is reachable as `client.<opId>`.
  // The runtime CLI/UX layer (formatter, exit codes, auth flag wiring)
  // lands in #768.
  return `\
// Generated by clesty. Do not edit.
// deno-lint-ignore-file no-explicit-any

import * as sdk from "./generated/sdk.gen.ts";

type Action = (opts: any) => void | Promise<void>;
type CmdOpt = { flag: string; description: string; required: boolean };
type Cmd = {
  name: string;
  description: string;
  opts: CmdOpt[];
  action: Action | null;
};

const commands: Cmd[] = [];
let current: Cmd | null = null;

const program = {
  command(name: string, description: string = "") {
    current = { name, description, opts: [], action: null };
    commands.push(current);
    return chain;
  },
};

const chain = {
  requiredOption(flag: string, description: string) {
    current!.opts.push({ flag, description, required: true });
    return chain;
  },
  option(flag: string, description: string) {
    current!.opts.push({ flag, description, required: false });
    return chain;
  },
  action(fn: Action) {
    current!.action = fn;
    return chain;
  },
};

const client = sdk as any;

${codegenSource}

function parseFlags(opts: CmdOpt[], rest: string[]): Record<string, string> {
  const out: Record<string, string> = {};
  const byFlag: Record<string, CmdOpt> = {};
  for (const o of opts) {
    const head = o.flag.split(/\\s+/, 1)[0];
    byFlag[head] = o;
  }
  for (let i = 0; i < rest.length; i++) {
    const a = rest[i];
    const opt = byFlag[a];
    if (!opt) throw new Error(\`unknown option: \${a}\`);
    const v = rest[++i];
    if (v === undefined) throw new Error(\`option \${a} requires a value\`);
    const name = a.replace(/^--/, "");
    out[name] = v;
  }
  for (const o of opts) {
    if (!o.required) continue;
    const head = o.flag.split(/\\s+/, 1)[0].replace(/^--/, "");
    if (!(head in out)) throw new Error(\`required option missing: --\${head}\`);
  }
  return out;
}

function helpText(): string {
  const lines = ["Usage: <bin> <subcommand> [options]", "", "Subcommands:"];
  for (const c of commands) {
    lines.push(\`  \${c.name}  \${c.description ?? ""}\`);
  }
  return lines.join("\\n");
}

async function main() {
  const argv = (globalThis as any).Deno?.args ?? [];
  if (argv.length === 0 || argv[0] === "-h" || argv[0] === "--help") {
    console.log(helpText());
    return;
  }
  const sub = argv[0];
  const rest = argv.slice(1);
  if (rest.includes("--help") || rest.includes("-h")) {
    const c = commands.find((x) => x.name === sub);
    if (!c) {
      console.error(\`unknown subcommand: \${sub}\`);
      (globalThis as any).Deno?.exit(2);
      return;
    }
    console.log(\`Usage: <bin> \${sub} [options]\`);
    console.log("");
    console.log(c.description ?? "");
    if (c.opts.length > 0) {
      console.log("");
      console.log("Options:");
      for (const o of c.opts) {
        console.log(\`  \${o.flag}  \${o.description}\${o.required ? " (required)" : ""}\`);
      }
    }
    return;
  }
  const c = commands.find((x) => x.name === sub);
  if (!c) {
    console.error(\`unknown subcommand: \${sub}\`);
    (globalThis as any).Deno?.exit(2);
    return;
  }
  try {
    const opts = parseFlags(c.opts, rest);
    if (c.action) await c.action(opts);
  } catch (e) {
    console.error((e as Error).message);
    (globalThis as any).Deno?.exit(1);
  }
}

await main();
`;
}

type SpecSource =
  | { kind: "path"; path: string }
  | { kind: "remote"; url: string }
  | { kind: "stdin" };

/** Classify `args.spec`.
 *
 *   - `-` → stdin sentinel.
 *   - `http://` / `https://` URL → remote (fetch once into the bundle).
 *   - `file:` URL → converted to a path via `fromFileUrl` so ref-safety
 *     applies normally (otherwise a `file:` URL would let `$ref`s escape
 *     the spec's directory unchecked — a real security gap).
 *   - bare path → absolutized.
 */
function classifySpec(spec: string): SpecSource {
  if (spec === "-") return { kind: "stdin" };
  if (spec.startsWith("http://") || spec.startsWith("https://")) {
    return { kind: "remote", url: spec };
  }
  if (spec.startsWith("file:")) {
    return { kind: "path", path: fromFileUrl(spec) };
  }
  return { kind: "path", path: isAbsolute(spec) ? spec : resolve(spec) };
}

/** Rewrite an error's `origin` (and `message` substring) from a temp
 * path to `<stdin>` so the caller sees the spec identifier they
 * actually passed (#107 contract: stream origins surface as `<stdin>`,
 * not the temp file the orchestrator chose to materialize them to). */
function withOrigin<E extends Error & { origin?: string }>(
  err: E,
  realOrigin: string,
  visibleOrigin: string,
): E {
  if (err.origin === realOrigin) err.origin = visibleOrigin;
  if (typeof err.message === "string" && err.message.includes(realOrigin)) {
    err.message = err.message.split(realOrigin).join(visibleOrigin);
  }
  return err;
}

/** Compile a spec into a self-contained binary at `args.output`. */
export async function compile(args: CompileArgs): Promise<void> {
  const spec = classifySpec(args.spec);

  // The bundle tmp dir holds the hey-api SDK output, the composed
  // entry.ts, and (for stdin specs) the materialized spec file.
  const tmp = await Deno.makeTempDir({ prefix: "clesty-bundle-" });

  try {
    // Materialize once → all consumers read from the same on-disk bytes.
    // Closes #766's stream-handoff scope item AND the URL-TOCTOU concern:
    // stdin gets drained into a temp file; remote URLs get fetched once
    // and written to a temp file; on-disk paths use the file the caller
    // named. After this step `input` is always a local path that
    // preflight, ref-safety, codegen, and hey-api all read.
    //
    // `origin` is the user-visible identifier — the path/URL the caller
    // typed, or `<stdin>` for stream input. Errors get rewritten so the
    // surfaced `.origin` matches what the user actually typed, not the
    // temp file the orchestrator chose internally (#107 contract).
    let input: string;
    let origin: string;
    if (spec.kind === "stdin") {
      const bytes = new Uint8Array(await new Response(Deno.stdin.readable).arrayBuffer());
      input = join(tmp, "stdin-spec.yaml");
      await Deno.writeFile(input, bytes);
      origin = "<stdin>";
    } else if (spec.kind === "remote") {
      const res = await fetch(spec.url);
      if (!res.ok) {
        // Cancel the unread body before throwing so the connection
        // doesn't leak.
        try {
          await res.body?.cancel();
        } catch { /* ignore */ }
        throw new Error(`fetch ${spec.url} failed: ${res.status} ${res.statusText}`);
      }
      const bytes = new Uint8Array(await res.arrayBuffer());
      input = join(tmp, "remote-spec.yaml");
      await Deno.writeFile(input, bytes);
      origin = spec.url;
    } else {
      input = spec.path;
      origin = spec.path;
    }

    // 1. Preflight (#107). Rewrite origin if it's a materialized input.
    const rewriteOrigin = origin !== input;
    try {
      await Preflight.check(input);
    } catch (e) {
      if (rewriteOrigin) {
        throw withOrigin(e as Error & { origin?: string }, input, origin);
      }
      throw e;
    }

    // 2. Ref-safety (#241) runs for ALL source kinds:
    //   - path: allowed root = caller's --allow-ref-root or the spec's
    //           own enclosing directory (the existing default).
    //   - stdin/remote: allowed root = caller's --allow-ref-root if
    //           given, otherwise the bundle tmp dir (which contains
    //           only the materialized spec). With root=tmp, hash-only
    //           refs (`#/...`) still resolve, but any external ref
    //           (absolute path, `file://`, parent escape) is refused.
    //           This closes the "malicious doc with $ref:/etc/passwd
    //           on stdin/remote" hole.
    const allowRefRoot = args.allowRefRoot ??
      (spec.kind === "path" ? undefined : tmp);
    try {
      await checkRefSafety(input, { allowRefRoot });
    } catch (e) {
      if (rewriteOrigin && e instanceof RefEscapesRoot) {
        // The error message embeds the temp file's containing dir.
        // Rewrite to the user-visible identifier so the surfaced text
        // matches what the caller typed.
        e.message = e.message.split(input).join(origin);
      }
      throw e;
    }

    // 3. Codegen (#130 etc.) — input is always a local path now.
    const result = await emit(input);

    // 4. hey-api: produce the typed SDK at <tmp>/generated/. Wrap any
    // throw as Compile.HeyApiFailure so callers get a uniform error
    // surface (#107 §"Errors"). Hey-api gets the local path; the
    // surfaced origin is the user-visible identifier.
    try {
      await createClient({
        input,
        output: { path: join(tmp, "generated") },
        plugins: ["@hey-api/client-fetch"],
      });
    } catch (cause) {
      throw new Compile.HeyApiFailure(origin, cause);
    }

    // 5. Compose the entry — the `import "./generated/sdk.gen.ts"` is
    // resolved by deno compile inside the tmp dir.
    const entry = composeEntry(result.source);
    const entryPath = join(tmp, "entry.ts");
    await Deno.writeTextFile(entryPath, entry);

    // 6. deno compile → self-contained binary at args.output.
    // --sloppy-imports because hey-api's generated TS uses Node-style
    // relative imports without `.ts` extensions; Deno requires explicit
    // extensions otherwise.
    const compileCmd = new Deno.Command(Deno.execPath(), {
      args: [
        "compile",
        "--quiet",
        "--allow-net",
        "--sloppy-imports",
        "--output",
        args.output,
        entryPath,
      ],
      stdout: "piped",
      stderr: "piped",
    });
    const out = await compileCmd.output();
    if (out.code !== 0) {
      const stderr = new TextDecoder().decode(out.stderr);
      throw new Error(`deno compile failed (exit ${out.code}):\n${stderr}`);
    }
  } finally {
    // Best-effort cleanup. Catching here is intentional: a removal
    // failure (permissions, race, already-deleted) must not mask the
    // real error from the try-block above.
    try {
      await Deno.remove(tmp, { recursive: true });
    } catch { /* ignore */ }
  }
}

/** Top-level dispatcher: argv[0] is the verb. */
export async function main(argv: string[]): Promise<number> {
  if (argv.length === 0 || argv[0] === "-h" || argv[0] === "--help") {
    console.log(USAGE);
    return 0;
  }
  const verb = argv[0];
  if (verb !== "compile") {
    console.error(`unknown verb: ${verb}\n\n${USAGE}`);
    return 2;
  }

  let parsed: CompileArgs;
  try {
    parsed = parseCompileArgs(argv.slice(1));
  } catch (e) {
    if (e instanceof UsageError) {
      if (e.message === "__HELP__") {
        console.log(USAGE);
        return 0;
      }
      console.error(`error: ${e.message}\n\n${USAGE}`);
      return 2;
    }
    throw e;
  }

  try {
    await compile(parsed);
    return 0;
  } catch (e) {
    const err = e as Error;
    const name = err.name ?? err.constructor?.name ?? "Error";
    // Surface error class name so test assertions match (#107, #241).
    console.error(`${name}: ${err.message}`);
    if (
      err instanceof Compile.MissingVersion ||
      err instanceof Compile.InvalidVersion ||
      err instanceof Compile.UnsupportedVersion
    ) return 3;
    if (err instanceof RefEscapesRoot) return 4;
    // HeyApiFailure + any other late-stage failure (codegen, bundle)
    // shares exit code 5 — the user-visible distinction comes from the
    // error name in stderr, not the exit code.
    return 5;
  }
}

if (import.meta.main) {
  const code = await main(Deno.args);
  Deno.exit(code);
}
